In [35]:
# carpeta de drive con imagenes: 
# https://drive.google.com/drive/folders/1v4V4WuqLqjzT-V2j6jRMzxD7C8Bu8H2X

# biblioteca opencv para el procesamiento de imagenes

import cv2

# biblioteca para las rutas del sistema (integrada en python)

import pathlib

# biblioteca scikit-learn para los clasificadores

from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler 

# biblioteca matplotlib para graficas y otras utilidades matemáticas

import matplotlib.pyplot as plt

# biblioteca numpy para los arreglos y otras utilidades matemáticas

import numpy as np

# biblioteca pandas para los datasets 

import pandas as pd

# la ruta especifica de la imagen siendo "images" la ruta donde guardamos las imagenes
route_img = str('images') 
#print(route_img)

In [19]:
# billeton.png es el nombre de la imagen por defecto
# el metodo retorna el objeto cv2 de la imagen especificadoa
def load_img(name="billeton.png"):
    return cv2.imread(route_img+'/'+name,1)

# El metodo muestra la imagen especificada
# recibe un objeto cv2 y el nombre de la ventana, por defecto "imagen"
def display_img(img,name="imagen"):
    cv2.imshow(name,img)
    cv2.waitKey()
    
#img = load_img('billeton.png')
#display_img(img)

In [20]:
# INTER_NEAREST
# INTER_LINEAR
# INTER_AREA
# INTER_CUBIC
# INTER_LANCZOS4
# percent of original size
def resize_img(img,scale_percent = 200, i = cv2.INTER_AREA):
    width = int(img.shape[1] * scale_percent / 100)
    height = int(img.shape[0] * scale_percent / 100)
    dim = (width, height)
    # resize image
    resized = cv2.resize(img, dim, interpolation = i)
    return resized

In [21]:
def resize_img(img,width = 800,height = 400, i = cv2.INTER_AREA):
    dim = (width, height)
    # resize image
    resized = cv2.resize(img, dim, interpolation = i)
    return resized

In [28]:
verdadero = load_img('Billetes_de_50/billete_50.jpg')
verdadero = resize_img(verdadero,i = cv2.INTER_LANCZOS4)
falso = load_img('billeteF_50/billeteF_50.jpg')
falso = resize_img(falso,i = cv2.INTER_LANCZOS4)


In [29]:
display_img(verdadero,"verdadero")
display_img(falso,"falso")
cv2.destroyAllWindows()

In [33]:
imgheight=verdadero.shape[0]
imgwidth=verdadero.shape[1]
image_copy = verdadero.copy()

#Recortando el billete
M = 200
N = 200
x1 = 0
y1 = 0

for y in range(0, imgheight, M):
    for x in range(0, imgwidth, N):
        if (imgheight - y) < M or (imgwidth - x) < N:
            break
            
        y1 = y + M
        x1 = x + N

        # check whether the patch width or height exceeds the image width or height
        if x1 >= imgwidth and y1 >= imgheight:
            x1 = imgwidth - 1
            y1 = imgheight - 1
            #Crop into patches of size MxN
            tiles = image_copy[y:y+M, x:x+N]
            #Save each patch into file directory
            cv2.imwrite(route_img + 'saved_patches/'+'tile'+str(x)+'_'+str(y)+'.jpg', tiles)
            cv2.rectangle(image_copy, (x, y), (x1, y1), (0, 255, 0), 1)
        elif y1 >= imgheight: # when patch height exceeds the image height
            y1 = imgheight - 1
            #Crop into patches of size MxN
            tiles = image_copy[y:y+M, x:x+N]
            #Save each patch into file directory
            cv2.imwrite(route_img + 'saved_patches/'+'tile'+str(x)+'_'+str(y)+'.jpg', tiles)
            cv2.rectangle(image_copy, (x, y), (x1, y1), (0, 255, 0), 1)
        elif x1 >= imgwidth: # when patch width exceeds the image width
            x1 = imgwidth - 1
            #Crop into patches of size MxN
            tiles = image_copy[y:y+M, x:x+N]
            #Save each patch into file directory
            cv2.imwrite(route_img + 'saved_patches/'+'tile'+str(x)+'_'+str(y)+'.jpg', tiles)
            cv2.rectangle(image_copy, (x, y), (x1, y1), (0, 255, 0), 1)
        else:
            #Crop into patches of size MxN
            tiles = image_copy[y:y+M, x:x+N]
            #Save each patch into file directory
            cv2.imwrite(route_img + 'saved_patches/'+'tile'+str(x)+'_'+str(y)+'.jpg', tiles)
            cv2.rectangle(image_copy, (x, y), (x1, y1), (0, 255, 0), 1)

In [34]:
display_img(image_copy,"verdadero")
cv2.destroyAllWindows()

In [51]:
df = pd.read_csv('Billetes50C1.csv')
print(df)
target = df['b']
del df['b']
X_train, X_test, y_train, y_test = train_test_split(df.values, target, test_size=0.3, random_state=27)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

    c1  c2  c3  b
0    1   1   1  1
1    0   0   0  0
2    1   0   0  0
3    0   0   0  0
4    1   1   0  1
5    1   1   0  1
6    1   1   0  1
7    1   0   0  0
8    1   1   1  1
9    0   0   0  0
10   0   1   1  0
11   1   1   0  1
12   0   1   0  0
13   1   0   0  0
14   0   0   0  0
15   1   1   0  1
16   0   0   0  0
17   0   0   0  0
18   0   0   0  0
19   0   0   0  0
20   0   0   0  0
21   0   0   0  0
22   0   0   0  0
[[1 0 0]
 [0 0 0]
 [1 1 0]
 [1 1 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [1 0 0]
 [0 0 0]
 [1 0 0]
 [1 1 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 1 0]
 [1 1 0]
 [1 1 1]
 [0 0 0]
 [0 0 0]]
7     0
3     0
6     1
4     1
18    0
14    0
1     0
10    0
15    1
2     0
17    0
13    0
5     1
16    0
8     1
19    0
Name: b, dtype: int64
22    0
9     0
12    0
11    1
0     1
20    0
21    0
Name: b, dtype: int64


In [52]:
def get_accuracy(model, X, y):
  cv = KFold(n_splits=10, random_state=1, shuffle=True)
  scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
  print("Scores", scores)
  print('Accuracy: %.3f (%.3f)' % (np.mean(scores), np.std(scores)))

In [53]:
classifier = DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)
print("Decision tree classifier: ", classifier.score(X_train, y_train))
get_accuracy(classifier, df.values, target)


Decision tree classifier:  1.0
Scores [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Accuracy: 1.000 (0.000)


In [54]:
print("RandomForest classifier")
classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)
classifier.score(X_train,y_train)
get_accuracy(classifier, df.values, target)

RandomForest classifier
Scores [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Accuracy: 1.000 (0.000)


In [55]:
print("mlp classifier")
classifier = MLPClassifier(max_iter=400)
classifier.fit(X_train, y_train)
classifier.score(X_train, y_train)
#get_accuracy(classifier, X_train, y_train)

mlp classifier


C:\Users\Josue\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (400) reached and the optimization hasn't converged yet.
  warnings.warn(


1.0

In [56]:
print("KNeighborsClassifier")
model = KNeighborsClassifier(3)
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

KNeighborsClassifier
Accuracy: 0.8571428571428571


In [57]:
print("Ada")
classifier = AdaBoostClassifier()
classifier.fit(X_train, y_train)
classifier.score(X_train, y_train)
#get_accuracy(classifier, X_train, y_train)

Ada


1.0

In [58]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
# Initialize classifier:
gnb = GaussianNB()

# Train the classifier:
model = gnb.fit(X_train, y_train)
# Make predictions with the classifier:
predictive_labels = gnb.predict(X_test)
print(predictive_labels)

# Evaluate label (subsets) accuracy:
print(accuracy_score(y_test, predictive_labels))

[0 0 0 1 1 0 0]
1.0


In [42]:
from pathlib import Path
p = Path('images/billetes_de_50')
for child in p.iterdir(): 
    print(child)

images\billetes_de_50\50F1_ubicacion_ventanasTransp.png
images\billetes_de_50\50_marcaAgua.png
images\billetes_de_50\b51_1.jpg
images\billetes_de_50\billete de 50.jpg
images\billetes_de_50\billete de 50_10.jpg
images\billetes_de_50\billete de 50_11.jpg
images\billetes_de_50\billete de 50_12.jpg
images\billetes_de_50\billete de 50_13.jpg
images\billetes_de_50\billete de 50_14.jpg
images\billetes_de_50\billete de 50_15.jpg
images\billetes_de_50\billete de 50_2.jpg
images\billetes_de_50\billete de 50_3.jpg
images\billetes_de_50\billete de 50_4.jpg
images\billetes_de_50\billeteF_50.jpg
images\billetes_de_50\billeteF_50_2.jpg
images\billetes_de_50\billeteF_50_3.jpg
images\billetes_de_50\billeteF_50_4.jpg
images\billetes_de_50\billeteF_50_5.jpg
images\billetes_de_50\billeteF_50_6.jpg
images\billetes_de_50\billete_50.jpg
images\billetes_de_50\billete_50_10.jpg
images\billetes_de_50\billete_50_11.jpg
images\billetes_de_50\billete_50_12.jpg
images\billetes_de_50\billete_50_5.jpg
images\billetes